Crying with database elena
IngElenaKozlova/fast_api_tutorial pull request #5
Opened 2023-02-19 17:13 UTC by IngElenaKozlova

Check my code and if it's ok corfirm pull request please :)

2023-02-20 14:00 UTC, Ilyusmax requested changes
Something wrong, I'm not able to start the app

2023-02-20 14:03 UTC, Ilyusmax reviewed
I suggest change names in sql_author  from Author to AuthorDB, from sql_book to BookDB. 
Move class new class AuthorDB to models.author.py. Move new class BookDB to models.book.py

2023-02-22 14:49 UTC, IngElenaKozlova commented
> 

I've made changes. Please check my code again.

2023-03-15 18:01 UTC, Ilyusmax approved these changes

2023-03-15 18:01 UTC, merged